version: '3'

services:
  bot:
    image: docker.nater0214.com/ziiiii-bot:latest
    build:
      context: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - HOME_GUILD_ID=${HOME_GUILD_ID}
    env_file:
      - path: ./.env
        required: true
